"""
Main Flask application factory.
"""
from pathlib import Path

from flask import Flask
from flask_cors import CORS
from flask_socketio import SocketIO

from app.config import Config
from app.database import (SessionLocal, init_db, init_claims_db,
                          ensure_api_claim_columns, ensure_api_order_columns,
                          warn_if_stats_index_missing)
from app.models import User
from app.services import user_service
from sqlalchemy import func, select

import logging
import os


# ---------------------------------------------------------------------------
# Eventlet WSGI noise filter
# ---------------------------------------------------------------------------
# Suppresses eventlet's harmless EBADF warnings on socket shutdown.
#
# What these look like (this is the noise we're dropping):
#   server=kciade.online//socket.io/ client=10.26.182.132:60926 \
#       socket shutdown error: [Errno 9] Bad file descriptor
#
# Why they appear:
#   When a WebSocket connection ends (browser close, NAT timeout, CF
#   disconnect, etc.), eventlet's WSGI cleanup runs socket.shutdown(SHUT_WR)
#   on the connection. Often the kernel has already reaped the FD by then,
#   so shutdown() returns EBADF. The error is benign — the socket is gone,
#   the shutdown would have been a no-op. eventlet logs it anyway, which at
#   scale (hundreds of disconnects/hour from natural client churn) spams the
#   log and obscures real warnings.
#
# Why this is safe:
#   * The error message is generated by eventlet INSIDE its cleanup path —
#     the connection is already closed; nothing functional is affected.
#   * We filter ONLY this specific substring; every other warning, error,
#     and info message from eventlet, gunicorn, and the app passes through
#     unmodified.
#   * The filter is attached to gunicorn.error, eventlet, and eventlet.wsgi
#     loggers (eventlet's wsgi.Server.log routes through whichever was
#     passed in by gunicorn).
#   * The 10.X.X.X IPs in these messages are Render's internal proxy IPs,
#     not end-user IPs — they provide no actionable signal even if read.
# ---------------------------------------------------------------------------
class _EventletShutdownNoiseFilter(logging.Filter):
    _SUPPRESS_SUBSTRINGS = (
        'socket shutdown error: [Errno 9] Bad file descriptor',
    )

    def filter(self, record: logging.LogRecord) -> bool:
        # Never block a log line if we can't render it — fail-safe.
        try:
            msg = record.getMessage()
        except Exception:
            return True
        return not any(s in msg for s in self._SUPPRESS_SUBSTRINGS)


_NOISE_FILTER = _EventletShutdownNoiseFilter()
for _name in ('gunicorn.error', 'eventlet', 'eventlet.wsgi'):
    logging.getLogger(_name).addFilter(_NOISE_FILTER)


# ---------------------------------------------------------------------------
# Async mode detection
# Auto-detects environment: 'eventlet' for production, 'threading' for local.
# Can be overridden via SOCKETIO_ASYNC_MODE env var.
# ---------------------------------------------------------------------------
is_production = (
    os.environ.get('GUNICORN_CMD_ARGS') is not None or
    os.environ.get('SERVER_SOFTWARE', '').startswith('gunicorn') or
    os.environ.get('PORT') is not None  # Render sets this
)

if os.environ.get('SOCKETIO_ASYNC_MODE'):
    async_mode = os.environ.get('SOCKETIO_ASYNC_MODE')
elif is_production:
    async_mode = 'eventlet'
else:
    async_mode = 'threading'

socketio = SocketIO(
    # API-Claimer product connects from many origins (Stake mirrors, the
    # backend's own iframe origin, dashboards) with no Cloudflare in front, so
    # accept all origins there. The main product keeps its explicit allow-list.
    cors_allowed_origins=('*' if Config.API_CLAIMER_MODE else Config.ALLOWED_ORIGINS),
    async_mode=async_mode,
    # Engine.IO native ping (server → client). Loosened from the previous
    # 15s/15s (~30s disconnect deadline) to 25s/20s (~45s deadline) to
    # accommodate RDP / cloud-VDI users. On laptops with direct internet
    # the old values worked fine, but RDP introduces variable latency:
    #   • Double network hop (user → RDP gateway → backend)
    #   • Occasional 5-15s jitter spikes from shared-tenant cloud VMs
    #   • Chrome inside backgrounded RDP windows throttles JS timers,
    #     delaying pong replies
    #   • Some RDP/VDI gateways buffer small WebSocket frames
    # 25/20 matches the values other working claimers in the same space
    # use (proven battle-tested) and Cloudflare's 100s idle timeout still
    # has plenty of headroom. The frontend's own app-level heartbeat
    # (25s interval, 10s pong timeout, 2 misses → disconnect ≈ 60s) is
    # independent and remains as a defence-in-depth zombie detector.
    ping_interval=25,
    ping_timeout=20,
)

BASE_DIR = Path(__file__).resolve().parent
TEMPLATE_DIR = BASE_DIR.parent / "templates"


def create_app(config_class=Config):
    """Create and configure the Flask application."""
    app = Flask(__name__, template_folder=str(TEMPLATE_DIR))
    app.config.from_object(config_class)

    # API-Claimer: accept all origins (no Cloudflare; many connecting hosts).
    if config_class.API_CLAIMER_MODE:
        CORS(app, origins='*', supports_credentials=False)
    else:
        CORS(app, origins=config_class.ALLOWED_ORIGINS, supports_credentials=True)

    # SocketIO must be bound to the app before run() is used
    socketio.init_app(app)

    # Rate limiting — per-IP and per-username
    from app.rate_limit import limiter
    limiter.init_app(app)

    # Register blueprints
    from app.routes.main import main_bp
    from app.routes.api import api_bp
    from app.routes.internal import internal_bp, xr9k_bp
    from app.routes.websocket_routes import ws_bp
    from app.routes.sse_routes import sse_bp
    from app.routes.api_slots import api_slots_bp  # API-Claimer product
    from app.routes.api_customer import api_customer_bp  # slot-sales (bot + Mini App)
    # NOTE: the public OxaPay webhook lives on the BOT service (Service 2) now,
    # so the heavy/spammy callback traffic never hits this backend. Money is
    # still moved ONLY here, via the internal /api/xr9k/topup/credit endpoint,
    # which independently re-verifies with OxaPay before crediting.

    app.register_blueprint(main_bp)
    app.register_blueprint(api_bp)
    app.register_blueprint(internal_bp)
    app.register_blueprint(xr9k_bp)
    app.register_blueprint(ws_bp)
    app.register_blueprint(sse_bp)
    app.register_blueprint(api_slots_bp)  # API-Claimer product
    app.register_blueprint(api_customer_bp)  # slot-sales (bot + Mini App)

    # Register /_tmc namespace by importing the module (decorators self-register).
    from app.routes import tmc_routes  # noqa: F401

    # ── Global request-rate flood monitor (best-effort, alerts the admin) ──
    # Counts every incoming HTTP request (incl. WS handshakes) into a fixed-size
    # in-memory ring buffer and pings the admin if the 60s total crosses the
    # threshold. Wrapped so monitoring can NEVER break request handling.
    from app.utils.attack_monitor import record_request as _record_request

    @app.before_request
    def _attack_monitor_before_request():
        try:
            _record_request()
        except Exception:
            pass
        return None

    import logging

    # init_db() runs DDL (create_all) against Supabase. It is NOT safe on the
    # live request path — a slow pooler handshake here blocks worker boot past
    # Gunicorn's timeout, which is what made Render fail to detect the port.
    # Gate it behind RUN_INIT_DB=1 so it only runs on explicit first-deploy.
    try:
        with app.app_context():
            if os.environ.get('RUN_INIT_DB') == '1':
                init_db()
                # Ensure the claims table on the SECOND DB (no-op if
                # CLAIMS_DATABASE_URL unset; never raises — degrades to the
                # in-memory fallback rather than blocking boot).
                init_claims_db()
            # Self-heal the api_claims ownership-snapshot column on EVERY boot in
            # API_CLAIMER_MODE (idempotent ADD COLUMN IF NOT EXISTS) so an existing
            # DB gets it without a manual migration / RUN_INIT_DB re-run. Cheap and
            # non-fatal; needed before /stats or any claim recording runs.
            if Config.API_CLAIMER_MODE:
                ensure_api_claim_columns()
                ensure_api_order_columns()      # cart_id for multi-slot carts (idempotent)
                # Read-only: warn (once) if the operational stats index is missing.
                # Never builds/locks/blocks — the index ships via MIGRATIONS.md.
                warn_if_stats_index_missing()
            user_service.start()
    except Exception as e:
        logging.error(
            f"Error during database/service initialization: {e}",
            exc_info=True
        )



    # Send startup notification to Telegram channel
    try:
        from app.utils.telegram import notify_startup
        notify_startup()
    except Exception as e:
        import logging as _log
        _log.warning(f"Telegram startup notify failed: {e}")

    return app


# ---------------------------------------------------------------------------
# Worker 1: Active-Disconnect-Worker
# Runs every 120 seconds.
# Checks only CURRENTLY CONNECTED users (WebSocket + SSE) against DB.
# 120s is a deliberate tradeoff against Supabase Free's Nano pooler (15 backend
# slots) — a 10s cadence produced periodic `Connection timed out` bursts when
# this worker coincided with cache sweeps and user lookups. 120s gives the
# pooler breathing room and still kicks revoked users within ~2 minutes.
# ---------------------------------------------------------------------------

def _start_active_disconnect_worker(app):
    """
    Background worker that disconnects users removed from the database.

    Scope: users who are CURRENTLY connected via WebSocket or SSE.
    Interval: every 120 seconds — tuned for Supabase Free's 15-slot pooler.

    For each cycle:
      1. Snapshots all connected WebSocket + SSE usernames.
      2. Single batch DB query to find which still exist.
      3. Guards against transient DB failures (distinguishes DB-down from
         user-genuinely-deleted via a health-check count query).
      4. Evicts removed users from UserService cache BEFORE disconnecting
         so that an immediate reconnect attempt hits DB and is rejected.
      5. Terminates their WebSocket connections.
      6. Terminates their SSE connections.
    """
    import threading
    import time
    import logging

    logger = logging.getLogger(__name__)

    # API_CLAIMER_MODE: this is a MAIN-PRODUCT reaper that validates connected
    # clients against the legacy app_users table. In API-Claimer mode the only
    # non-/_tmc client is the operator's ingest console (username 'ingest'), which
    # isn't an app_user — so this worker would disconnect it every cycle. Skip it
    # entirely (userscript account removal is handled by license_deleted events).
    if Config.API_CLAIMER_MODE:
        logger.info("Active-Disconnect-Worker NOT started (API_CLAIMER_MODE)")
        return

    def active_disconnect_loop():
        from app.websocket_manager import websocket_manager
        from app.sse_manager import sse_manager
        from app import socketio
        from app.config import Config

        while True:
            try:
                time.sleep(120)

                # Heartbeat — confirms the worker greenlet is alive and
                # cycling. If you don't see this every ~2 minutes in logs,
                # the worker is dead/starved and that's why nothing gets
                # disconnected.
                logger.info("Active disconnect: cycle start")

                # ----------------------------------------------------------
                # Step 1: Snapshot connected users — WebSocket
                # dict() copy: safe to iterate even if clients mutated
                # concurrently.
                # ----------------------------------------------------------
                connected_users = set()
                sids_to_disconnect = []

                clients_snapshot = dict(websocket_manager.clients)
                for sid, client_info in clients_snapshot.items():
                    username = client_info.get('username')
                    if username:
                        connected_users.add(username)

                # ----------------------------------------------------------
                # Step 2: Snapshot connected users — SSE
                # Lock held only for the copy; released before any DB work.
                # ----------------------------------------------------------
                # Derive the SSE snapshot from connection_health rather than
                # connections. In production we observed self.connections going
                # empty while self.connection_health remained populated — the
                # three dicts drifted out of sync under heavy greenlet
                # concurrency even though add_connection/remove_connection hold
                # the lock. connection_health is the dict /sse-pong looks up,
                # so if a connection can pong, it's live — that makes it the
                # reliable source of truth for "who is actually connected".
                with sse_manager.lock:
                    sse_snapshot = {}
                    for conn_id, health in sse_manager.connection_health.items():
                        username = health.get('username')
                        if not username:
                            continue
                        sse_snapshot.setdefault(username, []).append(conn_id)
                for username in sse_snapshot:
                    if username:
                        connected_users.add(username)

                # /_v snapshot — sid->username for the new broadcast namespace
                from app._v_manager import _v_manager
                v_snapshot = {}
                for sid, username in _v_manager.all_sids():
                    if not username:
                        continue
                    v_snapshot.setdefault(username, []).append(sid)
                    connected_users.add(username)

                logger.info(
                    f"Active disconnect: {len(connected_users)} connected users "
                    f"({len(clients_snapshot)} WS, {len(sse_snapshot)} SSE, "
                    f"{len(v_snapshot)} V) | "
                    f"sse_mgr_id={id(sse_manager)} | "
                    f"ws_mgr_id={id(websocket_manager)} | "
                    f"pid={os.getpid()}"
                )

                if not connected_users:
                    continue

                # ----------------------------------------------------------
                # Step 3: Skip when auth is disabled
                # ----------------------------------------------------------
                if Config.AUTH_DISABLED:
                    logger.info("Active disconnect: AUTH_DISABLED=true — skipping")
                    continue

                # ----------------------------------------------------------
                # Step 4: Batch DB query — one round-trip for all connected
                # ----------------------------------------------------------
                try:
                    with app.app_context():
                        from app.database import SessionLocal
                        with SessionLocal() as session:
                            valid_users = session.execute(
                                select(User.username).where(
                                    User.username.in_(connected_users)
                                )
                            ).scalars().all()
                            valid_users_set = set(valid_users)

                            # ----------------------------------------------
                            # Transient failure guard:
                            # If none of the connected users were found, the
                            # DB may be returning bad results rather than all
                            # users being genuinely deleted simultaneously.
                            # Verify with a cheap count before disconnecting.
                            # ----------------------------------------------
                            if not valid_users_set and connected_users:
                                try:
                                    db_alive = session.execute(
                                        select(func.count()).select_from(User)
                                    ).scalar()
                                    if db_alive == 0:
                                        logger.warning(
                                            "Active disconnect: DB health check "
                                            "shows 0 users — skipping "
                                            "(transient failure)"
                                        )
                                        continue
                                    # db_alive > 0: DB is up, users were
                                    # genuinely deleted — fall through.
                                except Exception:
                                    logger.warning(
                                        "Active disconnect: DB health check "
                                        "failed — skipping (transient failure)"
                                    )
                                    continue

                            users_to_disconnect = connected_users - valid_users_set

                            logger.info(
                                f"Active disconnect: DB returned {len(valid_users_set)} "
                                f"valid users out of {len(connected_users)} connected; "
                                f"{len(users_to_disconnect)} to disconnect"
                            )

                            if not users_to_disconnect:
                                continue

                            # ----------------------------------------------
                            # Step 5: Evict from cache BEFORE disconnecting.
                            # If an evicted user immediately tries to
                            # reconnect after being kicked, get_user() goes
                            # back to DB and correctly rejects them.
                            # ----------------------------------------------
                            for username in users_to_disconnect:
                                user_service.evict_user(username)

                            # ----------------------------------------------
                            # Step 6: Disconnect WebSocket connections
                            # ----------------------------------------------
                            for sid, client_info in clients_snapshot.items():
                                username = client_info.get('username')
                                if username and username in users_to_disconnect:
                                    sids_to_disconnect.append((
                                        sid,
                                        client_info.get('namespace', '/'),
                                        username
                                    ))

                            for sid, namespace, username in sids_to_disconnect:
                                try:
                                    socketio.server.disconnect(
                                        sid, namespace=namespace
                                    )
                                    websocket_manager.remove_client(sid)
                                    logger.info(
                                        f"Disconnected WebSocket: {username} "
                                        f"(removed from DB)"
                                    )
                                except Exception as e:
                                    logger.warning(
                                        f"Error disconnecting WebSocket "
                                        f"{username}: {e}"
                                    )

                            # ----------------------------------------------
                            # Step 7: Disconnect SSE connections
                            # O(1) dict.get() — not a linear scan.
                            # ----------------------------------------------
                            for username in users_to_disconnect:
                                try:
                                    conn_ids = sse_snapshot.get(username, [])
                                    for conn_id in conn_ids:
                                        sse_manager.remove_connection(
                                            username, conn_id
                                        )
                                        logger.info(
                                            f"Removed SSE: {username} "
                                            f"(removed from DB)"
                                        )
                                except Exception as e:
                                    logger.warning(
                                        f"Error removing SSE for {username}: {e}"
                                    )

                            # /_v eviction — disconnect WS sids for removed users
                            for username in users_to_disconnect:
                                for sid in v_snapshot.get(username, []):
                                    try:
                                        socketio.server.disconnect(
                                            sid, namespace='/_v'
                                        )
                                        logger.info(
                                            f"Disconnected /_v: {username} "
                                            f"(removed from DB)"
                                        )
                                    except Exception as e:
                                        logger.warning(
                                            f"Error disconnecting /_v "
                                            f"{username}: {e}"
                                        )

                except Exception as e:
                    logger.error(
                        f"Error in active disconnect worker: {e}",
                        exc_info=True
                    )

            except Exception as e:
                logger.error(
                    f"Error in active disconnect loop: {e}",
                    exc_info=True
                )
                time.sleep(60)  # Back off before retrying

    worker_thread = threading.Thread(
        target=active_disconnect_loop,
        daemon=True,
        name="Active-Disconnect-Worker"
    )
    worker_thread.start()
    logger.info("Active disconnect worker started")


# ---------------------------------------------------------------------------
# Slot-sales sweep (API_CLAIMER_MODE only) — capacity CLEANUP, not the auth
# boundary. Expires sold slots at/after expires_at (removing them from the
# operator's userscripts), releases stale unpaid reservations, and securely
# wipes any lingering pending tokens. Authorization always uses the live
# expires_at>now() predicate in each request, so this sweep only frees capacity.
# ---------------------------------------------------------------------------
def _start_slot_expiry_sweep(app):
    import threading
    import time
    import logging
    logger = logging.getLogger(__name__)

    def sweep_loop():
        from app.config import Config
        from app.database import db_session
        from app.models import ApiSlot, ApiOrder
        from sqlalchemy import select, or_
        interval = max(15, int(getattr(Config, 'SLOT_SWEEP_INTERVAL_S', 60)))
        while True:
            try:
                time.sleep(interval)
                from datetime import datetime, timezone
                now = datetime.now(timezone.utc)
                affected_keys = set()
                expired_notify = []   # [(telegram_id, stake_username)] for expiry DMs
                with db_session() as s:
                    # 1) Expire sold slots whose time is up.
                    rows = s.execute(
                        select(ApiSlot).where(ApiSlot.status == 'active',
                                              ApiSlot.expires_at.isnot(None),
                                              ApiSlot.expires_at <= now)
                    ).scalars().all()
                    for slot in rows:
                        slot.status = 'expired'
                        if slot.slot_telegram_id:
                            expired_notify.append(
                                (int(slot.slot_telegram_id), slot.stake_username or 'your account'))
                    # Token hygiene: once a subscription ends we no longer need the
                    # buyer's raw Stake credential. Wipe it on EVERY expired slot
                    # that still carries one (covers this cycle's expirations AND
                    # any historically-expired rows) so a dead subscription never
                    # leaves a live Stake token sitting in the DB / pushed to scripts.
                    # The userscript already ignores non-active slots, and a reuse
                    # overwrites the token anyway — so this is pure defense-in-depth.
                    from sqlalchemy import update as _update
                    s.flush()
                    tok_wiped = s.execute(
                        _update(ApiSlot)
                        .where(ApiSlot.status == 'expired',
                               ApiSlot.stake_access_token.isnot(None))
                        .values(stake_access_token=None, token_fp=None,
                                token_valid=False)
                    ).rowcount
                    if rows:
                        from app.models import ApiAccount
                        acct_ids = {r.account_id for r in rows}
                        accts = s.execute(
                            select(ApiAccount).where(ApiAccount.id.in_(acct_ids))
                        ).scalars().all()
                        affected_keys = {a.license_key for a in accts}
                    # 2) Release stale unpaid reservations + wipe their tokens.
                    stale = s.execute(
                        select(ApiOrder).where(
                            ApiOrder.status == 'pending',
                            ApiOrder.reservation_expires_at.isnot(None),
                            ApiOrder.reservation_expires_at <= now)
                    ).scalars().all()
                    for o in stale:
                        o.status = 'reservation_expired'
                        o.enc_stake_token = None
                        o.reserved_pool_account_id = None
                        o.reserved_slot_index = None
                        o.reservation_expires_at = None
                    # 3) Belt-and-suspenders: wipe tokens on any terminal order.
                    leftover = s.execute(
                        select(ApiOrder).where(
                            ApiOrder.status.in_(('failed', 'refunded', 'reservation_expired')),
                            ApiOrder.enc_stake_token.isnot(None))
                    ).scalars().all()
                    for o in leftover:
                        o.enc_stake_token = None
                    if rows or stale or leftover or tok_wiped:
                        logger.info(f"Slot-sweep: expired={len(rows)} "
                                    f"reservations_released={len(stale)} "
                                    f"order_tokens_wiped={len(leftover)} "
                                    f"slot_tokens_wiped={tok_wiped}")
                # Push updated slot lists to affected operator scripts (removes
                # the expired slot live).
                for lk in affected_keys:
                    try:
                        from app.routes.tmc_routes import push_slots_to_account
                        push_slots_to_account(lk)
                    except Exception:
                        pass
                # Notify each affected buyer (and the admin) that their slot expired.
                if expired_notify:
                    try:
                        from app.utils.telegram import notify_bot_service
                        admin_id = getattr(Config, 'ADMIN_TELEGRAM_ID', None)
                        for tid, uname in expired_notify:
                            try:
                                notify_bot_service(
                                    tid,
                                    f"⏰ <b>Subscription expired</b>\n"
                                    f"━━━━━━━━━━━━━━━\n"
                                    f"Your slot for <b>{uname}</b> just ran out, so we've "
                                    f"<b>stopped auto-claiming</b> for it. 😔\n\n"
                                    f"💸 Every drop from now on is a code you're missing.\n"
                                    f"⚡ Renew in seconds and we're back to claiming "
                                    f"<b>24×7</b> — you never lift a finger.\n\n"
                                    f"👉 Open the app, tap <b>{uname}</b>, and hit "
                                    f"<b>Renew</b> to pick up right where you left off. 🚀")
                            except Exception:
                                pass
                            if admin_id:
                                try:
                                    notify_bot_service(
                                        int(admin_id),
                                        f"🔔 Slot expired — user <code>{tid}</code> "
                                        f"(<b>{uname}</b>). Their subscription ended.")
                                except Exception:
                                    pass
                    except Exception:
                        logger.exception("expiry notify failed (ignored)")
                # Recover any MISSED OxaPay webhooks: re-verify pending orders that
                # already have a track_id and allocate if paid (no-op without an
                # OxaPay key configured on this backend).
                try:
                    from app.routes.api_customer import reconcile_pending_orders
                    n = reconcile_pending_orders()
                    if n:
                        logger.info(f"Slot-sweep: reconciled {n} paid order(s) from missed webhooks")
                except Exception:
                    logger.exception("slot reconcile failed (ignored)")
                # Auto-fulfil backordered slots (paid, waiting on capacity) now that this
                # sweep may have freed/added slots. Idempotent; DMs the buyer on activation.
                try:
                    from app.routes.api_customer import fulfil_awaiting_capacity
                    m = fulfil_awaiting_capacity()
                    if m:
                        logger.info(f"Slot-sweep: auto-activated {m} backordered slot(s)")
                except Exception:
                    logger.exception("backorder fulfil failed (ignored)")
            except Exception as e:
                logger.error(f"Error in slot expiry sweep: {e}", exc_info=True)
                time.sleep(30)

    t = threading.Thread(target=sweep_loop, daemon=True, name="Slot-Expiry-Sweep")
    t.start()
    logger.info("Slot expiry sweep worker started (API_CLAIMER_MODE)")


# ---------------------------------------------------------------------------
# Worker 2: Cache-Sweep-Worker
# Runs every 5 minutes.
# Checks ALL cached usernames (online AND offline) against DB.
# Catches deleted users who are currently offline — the active disconnect
# worker never sees them because they have no open connections.
#
# Example gap this closes:
#   1. Alice connects → get_user() caches Alice for 3 hours
#   2. Alice closes her browser (offline)
#   3. Admin deletes Alice from DB
#   4. Active-Disconnect-Worker: Alice not in connected_users → skipped
#   5. Cache-Sweep-Worker fires after ≤5 min → Alice in cache but not in
#      DB → evict_user("alice") → her cache entry removed
#   6. Alice tries to reconnect → cache miss → DB lookup → not found → 403
# ---------------------------------------------------------------------------

def _start_cache_sweep_worker(app):
    """
    Background worker that validates ALL cached users against DB every 5 min.

    Complements Active-Disconnect-Worker (which only checks connected users).
    Ensures deleted offline users are evicted from cache promptly, preventing
    them from reconnecting using a stale cache hit.

    Does NOT disconnect anyone — it only evicts cache entries. Active sessions
    are handled by Active-Disconnect-Worker. The next connection attempt by
    an evicted user will hit the DB and be rejected.
    """
    import threading
    import time
    import logging

    logger = logging.getLogger(__name__)

    # Sweep interval: 5 minutes is a good tradeoff.
    # Deleted offline users can reconnect for at most 5 minutes after deletion.
    _SWEEP_INTERVAL = 300  # seconds

    def cache_sweep_loop():
        from app.config import Config

        while True:
            try:
                time.sleep(_SWEEP_INTERVAL)

                if Config.AUTH_DISABLED:
                    continue

                # Get immutable snapshot of ALL currently cached usernames.
                # This is the full set — both connected and offline users.
                cached_usernames = user_service.get_all_cached_usernames()

                if not cached_usernames:
                    continue

                # Single batch query — one DB round-trip for the entire cache.
                try:
                    with app.app_context():
                        from app.database import SessionLocal
                        with SessionLocal() as session:
                            valid_users = session.execute(
                                select(User.username).where(
                                    User.username.in_(cached_usernames)
                                )
                            ).scalars().all()
                            valid_users_set = set(valid_users)

                            # Transient failure guard — same logic as the
                            # active disconnect worker. If DB returns an
                            # empty set for a non-empty cache, verify the
                            # table isn't genuinely empty before evicting.
                            if not valid_users_set and cached_usernames:
                                try:
                                    db_alive = session.execute(
                                        select(func.count()).select_from(User)
                                    ).scalar()
                                    if db_alive == 0:
                                        logger.warning(
                                            "Cache sweep: DB health check "
                                            "shows 0 users — skipping "
                                            "(transient failure)"
                                        )
                                        continue
                                except Exception:
                                    logger.warning(
                                        "Cache sweep: DB health check "
                                        "failed — skipping (transient failure)"
                                    )
                                    continue

                            # Users in cache but no longer in DB
                            stale_usernames = cached_usernames - valid_users_set

                            if not stale_usernames:
                                logger.debug(
                                    f"Cache sweep: {len(cached_usernames)} "
                                    f"cached users all valid"
                                )
                                continue

                            logger.info(
                                f"Cache sweep: evicting {len(stale_usernames)} "
                                f"stale user(s) from cache"
                            )
                            for username in stale_usernames:
                                user_service.evict_user(username)
                                logger.info(
                                    f"Cache sweep: evicted '{username}' "
                                    f"(no longer in DB)"
                                )

                except Exception as e:
                    logger.error(
                        f"Error in cache sweep DB query: {e}",
                        exc_info=True
                    )

            except Exception as e:
                logger.error(
                    f"Error in cache sweep loop: {e}",
                    exc_info=True
                )
                time.sleep(60)  # Back off before retrying

    sweep_thread = threading.Thread(
        target=cache_sweep_loop,
        daemon=True,
        name="Cache-Sweep-Worker"
    )
    # API_CLAIMER_MODE: main-product username/balance cache sweep — not needed.
    if not Config.API_CLAIMER_MODE:
        sweep_thread.start()
    logger.info(
        f"Cache sweep worker started — interval {_SWEEP_INTERVAL}s"
    )


# ---------------------------------------------------------------------------
# SSE stale connection cleanup
# ---------------------------------------------------------------------------

def _start_sse_cleanup_thread():
    """Start background thread to clean up stale SSE connections."""
    import threading
    import time
    import logging

    def cleanup_loop():
        from app.sse_manager import sse_manager
        while True:
            try:
                time.sleep(60)
                sse_manager.cleanup_stale_connections(timeout_seconds=300)
            except Exception as e:
                logging.error(f"Error in SSE cleanup loop: {e}")

    cleanup_thread = threading.Thread(
        target=cleanup_loop,
        daemon=True,
        name="SSE-Cleanup"
    )
    # API_CLAIMER_MODE: SSE transport is unused by the API-Claimer product.
    if not Config.API_CLAIMER_MODE:
        cleanup_thread.start()


# ---------------------------------------------------------------------------
# Worker 4: License-Activation-Scanner
# Runs every Config.LICENSE_SCAN_INTERVAL seconds.
# Detects new activations, deactivations, deletions, and field changes
# (e.g. maximum_usernames) in the licenses table. Notifies the bot service
# via /nx/v3/lic-sync and /nx/v3/push, and disconnects /_tmc rooms on
# deactivation / deletion.
# ---------------------------------------------------------------------------

def _start_license_activation_scanner(app):
    import threading
    import time
    import logging

    logger = logging.getLogger(__name__)

    # 30s grace at startup so the cache (rebuild_cache_from_db) settles and
    # we don't fire spurious "newly activated" notifications for licenses
    # already present in the cache from the boot snapshot.
    STARTUP_GRACE = 30.0

    def scanner_loop():
        from app.config import Config
        from app.database import SessionLocal
        from app.license_manager import (
            active_license_cache,
            _cache_lock,
            prune_denylist,
            redact_key,
        )
        from app.models import License
        from app.utils.telegram import notify_bot_service, push_license_sync
        from sqlalchemy import select, update

        # Per-license dedup for the <0.5 admin low-balance alert. A license is
        # added here when it first crosses below 0.5 and removed once it recovers
        # to >= 0.5, so the admin gets exactly one alert per downward crossing.
        low_alerted: set = set()

        # Engaging, user-friendly "you've run out of balance" notice. Sent once
        # per drain (the negative-balance path flips the license inactive, so it
        # cannot re-fire until a manual top-up + reactivation).
        def _neg_balance_msg(bal) -> str:
            """Engaging deactivation notice that states the ACTUAL (negative)
            balance. A single large claim can overshoot the top-up, so the
            balance can be well below $0 — we show exactly how much, plus how
            much it takes to get back to positive."""
            try:
                b = float(bal)
            except (TypeError, ValueError):
                b = 0.0
            need = abs(b) + 0.01  # nudge just past zero so it reactivates
            return (
                "🪫 <b>Balance Empty — License Paused</b>\n\n"
                "Your claiming balance just went <b>negative</b>, so your license "
                "has been <b>temporarily paused</b> to keep everything running "
                "smoothly. ⏸️\n\n"
                f"💳 Current balance: <b>${b:,.2f}</b>\n"
                "<i>Your last claim was larger than the balance you had left, so "
                "it dipped below zero.</i>\n\n"
                f"🔋 Add at least <b>${need:,.2f}</b> to get back above $0 and your "
                "license switches on automatically — no waiting. 🚀\n\n"
                "Tap /topup to recharge, or message @adityaofficial96 if you need a "
                "hand. 💛"
            )

        def _deactivate_for_negative_balance(lk, info) -> bool:
            """Disable a percentage license whose balance went negative, then
            tell the user (engagingly) to recharge. Handles DB, in-process cache,
            the /_tmc room, the bot cache sync, and the user notification — so the
            scanner's generic active-transition path must SKIP it (avoids a second
            'LICENSE DEACTIVATED' message).

            Returns True only if the DB write committed. On a DB failure it does
            NOT pop the cache, disconnect, sync, or notify — it returns False so
            the caller leaves the license untouched and the next scan cycle
            retries cleanly (no duplicate 'paused' message, no DB/notify desync)."""
            tid = int(info.get('telegram_id') or 0)
            try:
                with app.app_context():
                    with SessionLocal() as session:
                        session.execute(
                            update(License)
                            .where(License.license_key == lk)
                            .values(active=False, deactivated_at=func.now())
                        )
                        session.commit()
            except Exception as exc:
                logger.warning(
                    f"negative-balance deactivate failed for {redact_key(lk)}: {exc}"
                )
                return False
            with _cache_lock:
                active_license_cache.pop(lk, None)
            try:
                from app.routes.tmc_routes import disconnect_license_room
                disconnect_license_room(lk)
            except Exception:
                pass
            try:
                push_license_sync(lk, tid, False)
            except Exception:
                pass
            if tid:
                try:
                    notify_bot_service(tid, _neg_balance_msg(info.get('available_balance')))
                except Exception:
                    pass
            logger.info(
                f"BALANCE_DEACTIVATE | license={lk} | telegram_id={tid} | "
                f"balance={info.get('available_balance')}"
            )
            return True

        def _admin_low_balance_alert(lk, info):
            """DM ADMIN_TELEGRAM_ID that a percentage license is below $0.50."""
            admin_raw = (os.environ.get('ADMIN_TELEGRAM_ID') or '').strip()
            if not admin_raw:
                return
            try:
                admin_id = int(admin_raw)
            except (TypeError, ValueError):
                return
            tid = int(info.get('telegram_id') or 0)
            bal = info.get('available_balance')
            pct = info.get('deduction_percentage')
            msg = (
                "🔔 <b>LOW BALANCE ALERT</b>\n\n"
                "A license is running low and will need a top-up soon.\n\n"
                f"👤 User ID: <code>{tid}</code>\n"
                f"🔑 License: <code>{lk}</code>\n"
                f"💰 Balance: <b>${(bal if bal is not None else 0):.4f}</b>\n"
                f"📉 Deduction: <b>{(pct if pct is not None else 0):g}%</b> per claim"
            )
            try:
                notify_bot_service(admin_id, msg)
            except Exception:
                pass
            logger.info(
                f"LOW_BALANCE_ALERT | license={lk} | telegram_id={tid} | balance={bal}"
            )

        # Wait once before first scan
        time.sleep(STARTUP_GRACE)

        last_known: dict = {}
        # Build initial baseline against the live DB. Compare to the cache
        # which was loaded at startup so an activation that landed AFTER
        # boot-time snapshot still emits a notification (R-02).
        first_run = True

        while True:
            try:
                time.sleep(max(2, int(getattr(Config, 'LICENSE_SCAN_INTERVAL', 10))))

                with app.app_context():
                    with SessionLocal() as session:
                        all_lics = session.execute(select(
                            License.license_key, License.active, License.banned,
                            License.telegram_id, License.maximum_usernames,
                            License.theclaimers_count, License.manager_id,
                            License.available_balance, License.deduction_percentage,
                        )).all()
                        current = {
                            l.license_key: {
                                'active': bool(l.active),
                                'telegram_id': int(l.telegram_id),
                                'maximum_usernames': int(l.maximum_usernames or Config.MAX_CONNECTIONS_PER_LICENSE),
                                'theclaimers_count': int(l.theclaimers_count or 0),
                                'banned': bool(l.banned),
                                'manager_id': (l.manager_id or ''),
                                'available_balance': (float(l.available_balance) if l.available_balance is not None else 0.0),
                                'deduction_percentage': (float(l.deduction_percentage) if l.deduction_percentage is not None else None),
                            }
                            for l in all_lics
                        }

                if first_run:
                    # R-02: compare DB to cache to catch any activation that
                    # landed between rebuild_cache_from_db() and scanner start.
                    with _cache_lock:
                        cache_keys = set(active_license_cache.keys())
                    for lk, info in current.items():
                        in_cache = lk in cache_keys
                        if info['active'] and not info['banned'] and not in_cache:
                            # Newly activated since cache snapshot — notify
                            _emit_activation_notice(lk, info, notify_bot_service,
                                                    push_license_sync, redact_key)
                            with _cache_lock:
                                active_license_cache[lk] = {
                                    'active': True,
                                    'telegram_id': info['telegram_id'],
                                    'maximum_usernames': info['maximum_usernames'],
                                    'theclaimers_count': info['theclaimers_count'],
                                    'manager_id': info.get('manager_id', ''),
                                    'available_balance': info.get('available_balance'),
                                    'deduction_percentage': info.get('deduction_percentage'),
                                    'banned': False,
                                }
                        # Seed the low-balance dedup set so we DON'T fire alerts
                        # for licenses already below 0.5 at boot — we only alert
                        # on a fresh downward crossing after startup.
                        _pct = info.get('deduction_percentage')
                        _bal = info.get('available_balance')
                        if _pct is not None and _bal is not None and _bal < 0.5:
                            low_alerted.add(lk)
                    last_known = current
                    first_run = False
                    prune_denylist()
                    continue

                # Deletions: in last_known but missing from current
                for lk in set(last_known.keys()) - set(current.keys()):
                    prev = last_known.get(lk) or {}
                    telegram_id = prev.get('telegram_id') or 0
                    try:
                        from app.routes.tmc_routes import emit_license_deleted
                        emit_license_deleted(lk)
                    except Exception:
                        pass
                    with _cache_lock:
                        active_license_cache.pop(lk, None)
                    push_license_sync(lk, telegram_id, None)

                # Changes
                for lk, info in current.items():
                    prev = last_known.get(lk)
                    pct = info.get('deduction_percentage')
                    bal = info.get('available_balance')
                    balance_deactivated = False

                    # ── Percentage-license balance management ──────────────
                    # After-Claims licenses (deduction_percentage IS NULL) are
                    # exempt: no balance to deduct, police, or alert on (their
                    # default balance of 0 must never trip the <0.5 alert).
                    if pct is not None and bal is not None:
                        # Negative balance → temporarily disable + recharge nudge.
                        # Guarded on `active` so it fires exactly once per drain.
                        # Only mark it deactivated if the DB write committed;
                        # otherwise leave it as-is and retry next cycle (no
                        # spurious notice, no DB/notify desync).
                        if bal < 0 and info['active']:
                            if _deactivate_for_negative_balance(lk, info):
                                info['active'] = False
                                balance_deactivated = True
                        # Low-balance admin alert, deduped via low_alerted; the
                        # flag clears once the balance recovers to >= 0.5 so a
                        # later drop alerts again. Gated on `active`: a brand-new
                        # (or paused) prepaid license sits at $0 by design and is
                        # NOT "running low" — only an ACTIVE, in-use license that
                        # dips below $0.50 is worth alerting on.
                        if bal < 0.5 and info['active']:
                            if lk not in low_alerted:
                                _admin_low_balance_alert(lk, info)
                                low_alerted.add(lk)
                        else:
                            low_alerted.discard(lk)
                    else:
                        low_alerted.discard(lk)

                    # Always refresh cache for active+not-banned (now carrying
                    # available_balance + deduction_percentage too).
                    if info['active'] and not info['banned']:
                        with _cache_lock:
                            active_license_cache[lk] = {
                                'active': True,
                                'telegram_id': info['telegram_id'],
                                'maximum_usernames': info['maximum_usernames'],
                                'theclaimers_count': info['theclaimers_count'],
                                'manager_id': info.get('manager_id', ''),
                                'available_balance': bal,
                                'deduction_percentage': pct,
                                'banned': False,
                            }
                    else:
                        with _cache_lock:
                            active_license_cache.pop(lk, None)

                    if prev is None:
                        # Brand new row — DON'T notify yet (it was just created
                        # via /api/xr9k/lic/reg, which leaves it inactive).
                        last_known[lk] = info
                        continue

                    if balance_deactivated:
                        # The negative-balance path already updated the DB, the
                        # cache, the /_tmc room, the bot cache, and notified the
                        # user. Skip the generic active-transition handling so the
                        # user gets ONE (recharge) message, not two.
                        continue

                    # Only ACTIVE transitions sync to the bot. We deliberately do
                    # NOT push on every balance change: the bot never reads the
                    # cached balance for a decision (it live-fetches from the
                    # backend on /balance), so a per-cycle push would be a pure
                    # detached-curl fork storm under load with zero benefit. The
                    # transition push carries bal/pct so activation keeps the
                    # bot's fallback copy reasonably fresh.
                    if prev.get('active') != info['active']:
                        push_license_sync(
                            lk, info['telegram_id'], bool(info['active']),
                            info['theclaimers_count'], info['maximum_usernames'],
                            bal, pct,
                        )

                        if info['active'] and not prev['active']:
                            _emit_activation_notice(lk, info, notify_bot_service,
                                                    push_license_sync, redact_key)
                        elif not info['active'] and prev['active']:
                            # Newly deactivated — disconnect /_tmc room
                            try:
                                from app.routes.tmc_routes import disconnect_license_room
                                disconnect_license_room(lk)
                            except Exception:
                                pass
                            notify_bot_service(
                                info['telegram_id'],
                                "🔴 <b>License Deactivated</b>\n"
                                "━━━━━━━━━━━━━━━\n"
                                f"🔑 <code>{redact_key(lk)}</code>\n\n"
                                "Your license has been switched off. Tap 🛟 Support "
                                "(@adityaofficial96) if you think this is a mistake."
                            )

                # Drop deleted licenses from the low-balance dedup set so it can
                # never grow unbounded as licenses churn over time.
                low_alerted.intersection_update(current.keys())
                last_known = current
                prune_denylist()

            except Exception as e:
                logger.error(f"License scanner error: {e}", exc_info=True)

    def _emit_activation_notice(lk, info, notify_bot_service, push_license_sync, redact_key):
        try:
            push_license_sync(
                lk, info['telegram_id'], True,
                info['theclaimers_count'], info['maximum_usernames'],
                info.get('available_balance'), info.get('deduction_percentage'),
            )
            notify_bot_service(
                info['telegram_id'],
                "🟢 <b>License Activated</b>\n"
                "━━━━━━━━━━━━━━━\n"
                f"🔑 <code>{redact_key(lk)}</code>\n\n"
                "You're all set! Use /drop to broadcast codes, /connected to see "
                "your claimers, and /count to track results.\n\nWelcome aboard! 🚀"
            )
        except Exception as exc:
            logger.warning(f"_emit_activation_notice: {exc}")

    scanner_thread = threading.Thread(
        target=scanner_loop,
        daemon=True,
        name="License-Scanner",
    )
    # API_CLAIMER_MODE: the License-Scanner is main-product (queries the licenses
    # table + balance and pushes to the bot) — do NOT start it against the new DB.
    if not Config.API_CLAIMER_MODE:
        scanner_thread.start()
        logger.info("License-Scanner started")
    else:
        logger.info("License-Scanner NOT started (API_CLAIMER_MODE)")
