"""
Central rate limiting with Flask-Limiter.

- Per-IP limits use the real client IP (Cloudflare-aware via CF-Connecting-IP / X-Forwarded-For).
- Per-username limits key by username extracted from the request.
  - RSA flow (ENABLE_RSA_AUTH=true): username is extracted from the Bearer token,
    HMAC-verified before use so it cannot be forged.
  - Plain flow (ENABLE_RSA_AUTH=false): username is read from the JSON body as before.
"""
import hashlib
import hmac
import time

from flask import request
from flask_limiter import Limiter

from app.utils.cloudflare import get_real_client_ip


def _extract_username_from_bearer(authorization_header: str) -> str | None:
    """
    Verify and extract the username from a Bearer session token.

    Token format: user:expiry:sha256_hmac  (generated by generate_iframe_token)

    Returns the username string only if the HMAC signature is valid and the
    token has not expired. Returns None for any invalid input.

    Cost: one HMAC-SHA256 (~3 µs). Runs before AES decryption so bad actors
    are rejected cheaply. Cannot be forged without knowing WS_SECRET.
    """
    if not authorization_header or not authorization_header.startswith('Bearer '):
        return None

    token = authorization_header[7:].strip()
    if not token:
        return None

    try:
        parts = token.split(':')
        # Token is always user:expiry:signature (3 parts).
        # SHA256 hex = 64 chars with no colons; expiry = integer; usernames are alphanumeric.
        if len(parts) != 3:
            return None

        user_part, expiry_str, signature = parts

        # Cheap expiry gate first — no crypto needed
        expiry = int(expiry_str)
        if time.time() > expiry:
            return None

        # HMAC verification — the only way to trust user_part
        from app.config import Config  # lazy import: runs at request time, no circular risk
        if not Config.WS_SECRET:
            return None

        payload = f"{user_part}:{expiry_str}"
        expected = hmac.new(
            Config.WS_SECRET.encode('utf-8'),
            payload.encode('utf-8'),
            hashlib.sha256,
        ).hexdigest()

        if not hmac.compare_digest(signature, expected):
            return None

        username = user_part.strip()
        if not username or len(username) > 64:
            return None

        return username

    except (ValueError, IndexError):
        return None


def get_username_key() -> str | None:
    """
    Rate limit key for /api/users/claims/convert-to-usd.

    RSA flow (ENABLE_RSA_AUTH=true):
        Body is encrypted: { "alice": { "encDataX": "...", "iv": "..." } }
        data.get("username") returns None because the outer key IS the username.
        We instead extract the username from the HMAC-verified Bearer token.

    Plain flow (ENABLE_RSA_AUTH=false):
        Body is plain JSON: { "username": "alice", ... }
        No Authorization header — falls through to body parse as before.

    Returns None when no username can be verified, so the per-username rate
    limit decorator exempts the request (the IP limit still applies, and
    convert_to_usd will reject the request for other reasons).
    """
    # RSA flow: try Bearer token first
    auth_header = request.headers.get('Authorization', '')
    if auth_header.startswith('Bearer '):
        username = _extract_username_from_bearer(auth_header)
        if username:
            return f"username:{username.lower()}"

    # Plain flow: read username from JSON body (unchanged behaviour)
    if not request.is_json:
        return None
    try:
        data = request.get_json(silent=True)
        username = (data or {}).get('username')
        if not username or not isinstance(username, str):
            return None
        return f"username:{username.strip().lower()}"
    except Exception:
        return None


def get_embed_stream_user_key() -> str | None:
    """
    Key for rate limits on /embed-stream: per user (from query param `user`).
    Returns None when user param is missing so the limit can be exempted.
    """
    user = request.args.get('user')
    if not user or not isinstance(user, str):
        return None
    return f"embed_stream:{user.strip().lower()}"


# Limiter is created without app; init_app() is called in create_app().
# Default key_func = get_real_client_ip so IP-based limits work behind Cloudflare.
limiter = Limiter(
    key_func=get_real_client_ip,
    default_limits=[],  # No global default; apply limits per-route
)
